apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    team: min-side
  name: dittnav-event-handler
  namespace: min-side
spec:
  envFrom:
    - configmap: loginservice-idporten
  image: {{version}}
  port: 8080
  liveness:
    failureThreshold: 3
    initialDelay: 30
    path: /dittnav-event-handler/internal/isAlive
    periodSeconds: 10
  readiness:
    initialDelay: 30
    path: /dittnav-event-handler/internal/isReady
  prometheus:
    enabled: true
    path: /dittnav-event-handler/metrics
  secureLogs:
    enabled: true
  replicas:
    max: 4
    min: 2
  resources:
    limits:
      cpu: "3"
      memory: 768Mi
    requests:
      cpu: "50m"
      memory: 384Mi
  ingresses:
    - "https://person.nav.no/dittnav-event-handler"
  gcp:
    permissions:
      - resource:
          apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
          kind: Project
        role: roles/cloudsql.client
    sqlInstances:
      - databases:
          - envVarPrefix: DB
            name: brukernotifikasjon-cache
            users:
              - name: eventhandler
        name: brukernotifikasjon-cache
        type: POSTGRES_11
        tier: db-custom-4-24576
        diskType: SSD
        highAvailability: true
        diskSize: 100
        diskAutoresize: true
        autoBackupTime: "03:00"
        maintenanceWindow:
          day: 1
          hour: 4
        cascadingDelete: false
  kafka:
    pool: nav-prod
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: dittnav-api
        - application: internal-periodic-metrics-reporter
        - application: dittnav-nightly-usage-statistics-reporter
        - application: tms-event-test-producer
        - application: dittnav-eventer-modia
          namespace: personbruker
          cluster: prod-fss
        - application: tms-event-api
        - application: tms-varselbjelle-api
        - application: tms-varsel-api
    outbound:
      external:
        - host: kafka-schema-registry.nais.adeo.no
    env:
      - name: GROUP_ID
        value: min-side-event-handler-001
      - name: OPEN_INPUT_DONE_TOPIC
        value: min-side.aapen-brukernotifikasjon-done-v1