version: '3.7'
services:

  postgres:
    image: "postgres:11"
    restart: "always"
    volumes:
      - "dittnav-event-cache-data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "test-admin"
      POSTGRES_PASSWORD: "testpassword"
      POSTGRES_DB: "dittnav-event-cache-preprod"

volumes:
  dittnav-event-cache-data: