apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dittnav-event-handler
  namespace: default
  labels:
    team: personbruker
spec:
  image: navikt/dittnav-event-handler:0.0.17
  team: personbruker
  port: 8080
  liveness:
    path: /isAlive
    initialDelay: 10
  readiness:
    path: /isReady
    initialDelay: 10
  prometheus:
    path: /metrics
  replicas:
    min: 2
    max: 4
  ingresses:
    - "https://dittnav-event-handler.dev-sbs.nais.io"
    - "https://dittnav-event-handler.nais.oera-q.local"
  vault:
    enabled: true
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi