apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dittnav-event-handler
  namespace: personbruker
  labels:
    team: personbruker
spec:
  envFrom:
    - configmap: loginservice-idporten
  image: {{version}}
  port: 8080
  liveness:
    path: /internal/isAlive
    initialDelay: 20
  readiness:
    path: /internal/isReady
    initialDelay: 20
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 4
    max: 4
  webproxy: true
  ingresses:
    - "https://dittnav-event-handler.nais.oera.no"
  vault:
    enabled: true
    paths:
      - kvPath: /kv/prod/sbs/dittnav-event-handler/personbruker
        mountPath: /var/run/secrets/nais.io/vault
      - kvPath: /serviceuser/data/prod/srvdn-e-handler
        mountPath: /secret/serviceuser
  resources:
    limits:
      cpu: "3"
      memory: 768Mi
    requests:
      cpu: "50m"
      memory: 384Mi
