apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dittnav-event-handler
  namespace: {{namespace}}
  labels:
    team: {{team}}
spec:
  image: {{version}}
  port: 8080
  liveness:
    path: /isAlive
    initialDelay: 5
  readiness:
    path: /isReady
    initialDelay: 5
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 1
    max: 1
  webproxy: true
  ingresses: {{ingresses}}
  vault:
    enabled: true
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
