apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dittnav-event-handler
  namespace: {{namespace}}
  labels:
    team: {{team}}
spec:
  image: {{version}}
  port: 8080
  liveness:
    path: /isAlive
    initialDelay: 5
  readiness:
    path: /isReady
    initialDelay: 5
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 2
    max: 4
  webproxy: true
  ingresses: {{ingresses}}
  vault:
    enabled: true
  resources:
    limits:
      cpu: "1"
      memory: 768Mi
    requests:
      cpu: "500m"
      memory: 384Mi
