apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    team: min-side
  name: dittnav-event-handler
  namespace: min-side
  annotations:
    config.alpha.linkerd.io/proxy-wait-before-exit-seconds: "10"
spec:
  envFrom:
    - secret: dittnav-event-handler-secrets
    - configmap: loginservice-idporten
  image: {{version}}
  port: 8080
  liveness:
    failureThreshold: 3
    initialDelay: 30
    path: /dittnav-event-handler/internal/isAlive
    periodSeconds: 10
  readiness:
    initialDelay: 30
    path: /dittnav-event-handler/internal/isReady
  prometheus:
    enabled: true
    path: /dittnav-event-handler/metrics
  secureLogs:
    enabled: true
  replicas:
    max: 4
    min: 2
  resources:
    limits:
      cpu: "3"
      memory: 768Mi
    requests:
      cpu: "50m"
      memory: 384Mi
  ingresses:
    - "https://dittnav-event-handler.intern.dev.nav.no/dittnav-event-handler"
  gcp:
    permissions:
      - resource:
          apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
          kind: Project
        role: roles/cloudsql.client
    sqlInstances:
      - databases:
          - envVarPrefix: DB
            name: brukernotifikasjon-cache
            users:
              - name: eventhandler
        name: brukernotifikasjon-cache
        diskSize: 10
        diskType: SSD
        tier: db-f1-micro
        type: POSTGRES_11
  kafka:
    pool: nav-dev
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: dittnav-api
        - application: internal-periodic-metrics-reporter
        - application: dittnav-nightly-usage-statistics-reporter
        - application: tms-event-test-producer
        - application: dittnav-eventer-modia
          namespace: personbruker
          cluster: dev-fss
        - application: tms-event-api
        - application: tms-varselbjelle-api
        - application: tms-varsel-api
    outbound:
      external:
        - host: kafka-schema-registry.nais-q.adeo.no
